### ISSUE TITLE
Optimization problems with gcc 6.1.1

### ISSUE THREAD

**Issue by chron-isch** [AD-Vega/rtl-power-fftw#14]
Hi, 

I'm new to the whole SDR field and in the process of settings everything up so I can play/explore and learn a few things.

I'm trying to use my 820T with a Raspberry Pi 2 running ArchLinux(Linux 4.4.11-3-ARCH #1 SMP Wed May 25 18:50:04 MDT 2016 armv7l GNU/Linux).
The problem is that rtl_power_fftw segfaults almost right after setting the frequency on the device.

gcc version 6.1.1 20160501 (GCC) 
tclap 1.2.1
fftw 3.3.4

Just trying to run one of the examples from the man page (CMAKE_BUILD_TYPE=Release):
```
chron@* /home/chron % rtl_power_fftw -f 1420405752 -n 5 -b 512 -c
Found Rafael Micro R820T tuner
Available gains (in 1/10th of dB): 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496
Selected nearest available gain: 372 (37.2 dB)
Exact sample rate is: 2000000.052982 Hz
Actual sample rate: 2000000 Hz
Number of bins: 512
Total number of (complex) samples to collect: 2560
Buffer length: 16384
Number of averaged spectra: 5
Estimated time of measurements: 0.00128 seconds
Tuning to 1420405752 Hz (try 1)
Device tuned to: 1420405752 Hz
Acquisition started at 2016-05-31 08:51:34 UTC
[1]    32450 segmentation fault (core dumped)  rtl_power_fftw -f 1420405752 -n 5 -b 512 -c
```

Build with CMAKE_BUILD_TYPE=RelWithDebInfo
```
chron@* ...l-power-fftw/RelWithDebInfo % coredumpctl gdb /home/chron/builds/RTL-SDR/rtl_power_fftw-git/src/rtl-power-fftw/RelWithDebInfo/rtl_power_fftw
           PID: 385 (rtl_power_fftw)
           UID: 1000 (chron)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Di 2016-05-31 11:00:16 CEST (31s ago)
  Command Line: ./rtl_power_fftw -f 1420405752 -n 100 -b 512
    Executable: /home/chron/builds/RTL-SDR/rtl_power_fftw-git/src/rtl-power-fftw/RelWithDebInfo/rtl_power_fftw
 Control Group: /
         Slice: -.slice
       Boot ID: d54f6f6c5b7c4ba8958b1bc9a5dbba66
    Machine ID: 20d4f52b53de4dd9aa7ac72e93285b0a
      Hostname: sigint
      Coredump: /var/lib/systemd/coredump/core.rtl_power_fftw.1000.d54f6f6c5b7c4ba8958b1bc9a5dbba66.385.1464685216000000000000.lz4
       Message: Process 385 (rtl_power_fftw) of user 1000 dumped core.
                
                Stack trace of thread 388:
                #0  0x0000000076db1b24 pthread_mutex_lock (libpthread.so.0)

GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "armv7l-unknown-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/chron/builds/RTL-SDR/rtl_power_fftw-git/src/rtl-power-fftw/RelWithDebInfo/rtl_power_fftw...done.
[New LWP 388]
[New LWP 385]
[New LWP 387]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./rtl_power_fftw -f 1420405752 -n 100 -b 512'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x76db1b24 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
[Current thread is 1 (Thread 0x761fc450 (LWP 388))]
(gdb) bt full
#0  0x76db1b24 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x0001dee4 in __gthread_mutex_lock (__mutex=<optimized out>) at /usr/include/c++/6.1.1/armv7l-unknown-linux-gnueabihf/bits/gthr-default.h:748
No locals.
#2  std::mutex::lock (this=<optimized out>) at /usr/include/c++/6.1.1/bits/std_mutex.h:103
No locals.
#3  std::unique_lock<std::mutex>::lock (this=0x761fbe18) at /usr/include/c++/6.1.1/bits/std_mutex.h:267
No locals.
#4  Datastore::fftThread (this=0x0) at /home/chron/builds/RTL-SDR/rtl_power_fftw-git/src/rtl-power-fftw/src/datastore.cxx:55
        buffer = <optimized out>
        buffer_pointer = <optimized out>
        status_lock = {_M_device = 0x10, _M_owns = false}
        fft_pointer = 0
#5  0x76cfcefc in std::execute_native_thread_routine (__p=0x1d7a18) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
        __t = std::unique_ptr<std::thread::_State> containing 0x1d7a18
#6  0x76daefac in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#7  0x76b45cc0 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

But when I build with CMAKE_BUILD_TYPE=Debug instead of Release or RelWithDebInfo it works.
```
chron@* ...it/src/rtl-power-fftw/Debug % gdb ./rtl_power_fftw 
GNU gdb (GDB) 7.11
...
Reading symbols from ./rtl_power_fftw...done.
(gdb) run
Starting program: /home/chron/builds/RTL-SDR/rtl_power_fftw-git/src/rtl-power-fftw/Debug/rtl_power_fftw 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x76ab8450 (LWP 25041)]
[Thread 0x76ab8450 (LWP 25041) exited]
[New Thread 0x76ab8450 (LWP 25042)]
Found Rafael Micro R820T tuner
Available gains (in 1/10th of dB): 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496
Selected nearest available gain: 372 (37.2 dB)
Exact sample rate is: 2000000.052982 Hz
Actual sample rate: 2000000 Hz
Number of bins: 512
Total number of (complex) samples to collect: 819200
Buffer length: 1638400
Number of averaged spectra: 1600
Estimated time of measurements: 0.4096 seconds
Tuning to 1420405752 Hz (try 1)
Device tuned to: 1420405752 Hz
[New Thread 0x75ae3450 (LWP 25043)]
Acquisition started at 2016-05-30 15:55:36 UTC
Acquisition done at 2016-05-30 15:55:37 UTC
Actual number of (complex) samples collected: 819200
Actual number of device readouts: 1
Number of successful readouts: 1
Actual number of averaged spectra: 1600[Thread 0x75ae3450 (LWP 25043) exited]

Effective integration time: 0.4096 seconds
# rtl-power-fftw output
# Acquisition start: 2016-05-30 15:55:36 UTC
# Acquisition end: 2016-05-30 15:55:37 UTC
#
# frequency [Hz] power spectral density [dB/Hz]
1.41940575e+09 -33.1588
...
1.42140185e+09 -44.9864

Buffer queue histogram: 0 0 0 0 0 1 

[Thread 0x76ab8450 (LWP 25042) exited]
[Inferior 1 (process 25038) exited normally]
(gdb)6.4302
1.42114794e+09 -50.8536
... 
1.42140185e+09 -44.9864

Buffer queue histogram: 0 0 0 0 0 1 

[Thread 0x76ab8450 (LWP 25042) exited]
[Inferior 1 (process 25038) exited normally]
```

As far as I know, the main diffrence between RelWithDebInfo and Debug is compiler optimization, RelWithDebInfo has it turned on and Debug doesn't.

If you need any more info, I'm happy to help.

**Comment by alajovic** [comment]
Hey, @chron-isch,

thanks for your report. I have reproduced the problem on an Arch machine and was able to track it down and fix it. We were starting the FFT thread by passing to the constructor a pointer to the member function and a reference to the Datastore object - it turns out that the latter should have been a pointer rather than a reference. The original line of code was probably copied off the net and since it was not giving us any trouble, it remained there until a newer gcc version finally disagreed with our approach. :-) It seems to be related to this issue:

http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2219

The latest version in master fixes the problem for me. Please test and report back.

cheers,
andrej

**Comment by chron-isch** [comment]
Hey @alajovic,

thanks for the quick response. It works perfectly.

Thanks,
Alex
